### ISSUE TITLE
Confusion

### ISSUE THREAD

**Issue by cicku** [tapper/Tapper#3]
HI tapper team,

I'm planning packaging this, but I don't know hte connection between you and amd.

Since github.com/amd/Tapper in http://search.cpan.org/~amd/Tapper-4.1/ doesn't exist, can you tell me which one is the really upstream and can provide the latest goods?

Thanks.

**Comment by tapper** [comment]
I don't have resources for implementing requests, sorry, so I'm cleaning up the bug tracker, please reopen if your issue requires more attention. I'm happily accepting contribution pull requests though.
