### ISSUE TITLE
How Do you set the timezone?

### ISSUE THREAD

**Issue by seanmalloy** [tapper/Tapper#4]
It looks like the default timezone in the Tapper Web UI is set to GMT. How do you set a different timezone?

![tapper](https://f.cloud.github.com/assets/685221/2197980/8755ac68-98c2-11e3-95f2-65301296d891.png)

**Comment by tapper** [comment]
I don't have resources for implementing requests, sorry, so I'm cleaning up the bug tracker, please reopen if your issue requires more attention. I'm happily accepting contribution pull requests though.
