### ISSUE TITLE
bug in tapper-mcp-messagereceiver

### ISSUE THREAD

**Issue by miregit** [tapper/Tapper#5]
it fails to start (install)
    Can't locate object method "secret" via package "Mojolicious::Lite"

what is necessary is to edit this line

app->secret('Tapper::MCP::MessageReceiver');

to this and it will work

app->secrets(['Tapper::MCP::MessageReceiver']);

more info:
http://mojolicio.us/perldoc/Mojolicious#secrets
http://irclog.perlgeek.de/mojo/2014-04-20

**Comment by tapper** [comment]
I don't have resources for implementing requests, sorry, so I'm cleaning up the bug tracker, please reopen if your issue requires more attention. In this case I *think* we fixed it long ago, if not, then, erm, not.
