### ISSUE TITLE
Tapper and sparrowhub integration, collaboration request .

### ISSUE THREAD

**Issue by melezhik** [tapper/Tapper#6]
Hi tapper guys!

I found a quite lot of activity  of Tapper::\* updates recently on
metacpan, and so assuming that tapper project is in active
development?
If so, and If I understood tap concept correctly, would you please
take a look at possible sparrowhub integration?

Why?

I thinks tapper / sparrowhub could be good match, as:
- sparrowhub -  https://sparrowhub.org - is repository of   reusable
  tests suites for any kinds of testing cases ( web applications,
  console clients, text verification, etc  )
- sparrowhub infrastructure -  https://github.com/melezhik/sparrow
  could be easily integrated with tapper via preconditions
- sparrowhub environment is very close to tapper one. I mean
  sparrowhub suites are written on perl, emit TAP; sparrow manager
  installed as cpan module. So integration part probably would be chip
  and easy.
- sparrow plugins are divided into basic parts - generic testing
  plugins and web application testing plugins, both of type is based on
  rich text verification DSL -
  https://github.com/melezhik/outthentic-dsl
- consider possible new plugins development for **OS  testing** (
  analyzing unstructured output from bash commands ( ps, df, mount, etc.
  ) Outthentic dsl is specially designed for such a tasks ( let me know
  if you need some examples on it   )
- both tapper and sparrowhub are about testing automation but for
  different contexts , but they could be combined!

Regards and thanks in advance for you feedback

Alexey Melezhik

PS links for documentation
- sparrowhub repository - https://sparrowhub.org/
- outthentic dsl - https://github.com/melezhik/outthentic-dsl
- web application testing framework based on outthentic dsl -
  https://github.com/melezhik/swat
- generic testing framework based on outthentic dsl -
  https://github.com/melezhik/outthentic

**Comment by renormalist** [comment]
Just for the records: as discussed per email - please bump me again in a couple of weeks when I'm out of the release polishing peak to make up my mind. Thanks.

**Comment by melezhik** [comment]
sure

**Comment by melezhik** [comment]
Hi Steffen!

Any news for me?

Thanks

**Comment by melezhik** [comment]
Hi Steffen! Have not heard any activities from tapper, is project alive ?

**Comment by renormalist** [comment]
I use it mid-scale; Amazon uses a fork large-scale; I don't know much in between. It's alive enough for me, that's for sure; but I mostly do things *with* it, not *on* it. It's not my primary focus currently, except bug fixing.

Kind regards,
Steffen

**Comment by tapper** [comment]
I don't have resources for anything beyond my direct usage, sorry. Cleaning up issue tracker...
