### ISSUE TITLE
Website broken?

### ISSUE THREAD

**Issue by djzort** [tapper/Tapper#7]
The website seems broken

**Comment by renormalist** [comment]
Yep, sorry and thanks for reporting. In the meantime: http://tapper.github.io/Tapper/

**Comment by jdickey** [comment]
The github.io site has broken links. Of the seven links in the "Related material" section, only the 2011 [_Floss Weekly_](http://twit.tv/show/floss-weekly/241) link and the Perl [Hello World](https://github.com/tapper/Tapper/wiki/HelloWorld) still work. For people, not necessarily from a Perl background, considering adding Tapper to the toolchain for a project, this isn't the best practical first impression.

**Comment by tapper** [comment]
The related material should be back, in particular the presentations. Thanks for reporting.
